.apex/src/objects/Item__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Purchase__c.object
<CustomObject>
    <fields>
        <fullName>GrandTotal__c</fullName>
        <label>GrandTotal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TotalItems__c</fullName>
        <label>TotalItems</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Purchase</label>
    <nameField>
        <label>Purchase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

.apex/src/objects/PurchaseLine__c.object
<CustomObject>
    <fields>
        <fullName>PurchaseId__c</fullName>
        <label>Purchase</label>
        <referenceTo>Purchase__c</referenceTo>
        <relationshipLabel>PurchaseLines</relationshipLabel>
        <relationshipName>PurchaseLines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>PurchaseLine</label>
    <nameField>
        <label>PurchaseLine Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PurchaseLines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

.apex/src/classes/PurchaseServiceTest.cls
@isTest
private class PurchaseServiceTest {

	@testSetup
	static void setupData() {
		Account acc = new Account(Name = 'Test Account', Industry = 'Tech');
		insert acc;

		List<Item__c> items = new List<Item__c>{
				new Item__c(Name = 'Item A', Price__c = 100),
				new Item__c(Name = 'Item B', Price__c = 200)
				};
		insert items;
	}

	@isTest
	static void testCreatePurchase() {
		Account acc = [SELECT Id FROM Account LIMIT 1];
		List<Item__c> items = [SELECT Id FROM Item__c];

		Test.startTest();
		Id purchaseId = PurchaseService.createPurchase(acc.Id, new List<Id>{
				items[0].Id,
				items[1].Id
				});
		Test.stopTest();

		Purchase__c purchase = [
				SELECT TotalItems__c, GrandTotal__c
				FROM Purchase__c
				WHERE Id = :purchaseId
		];

		System.assertEquals(2, purchase.TotalItems__c, 'Should have 2 items');
		System.assertEquals(300, purchase.GrandTotal__c, 'Should total 300 USD');

		List<PurchaseLine__c> lines = [
				SELECT Id FROM PurchaseLine__c WHERE PurchaseId__c = :purchaseId
		];
		System.assertEquals(2, lines.size(), 'Should have 2 lines');
	}

	@isTest
	static void testNullInputThrowsError() {
		try {
			PurchaseService.createPurchase(null, new List<Id>());
			System.assert(false, 'Expected AuraHandledException');
		} catch (AuraHandledException e) {
			System.assert(e.getMessage().contains('Account and items are required'));
		}
	}
}