src/objects/Purchase__c.object
<CustomObject>
    <fields>
        <fullName>GrandTotal__c</fullName>
        <label>GrandTotal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TotalItems__c</fullName>
        <label>TotalItems</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Purchase</label>
    <nameField>
        <label>Purchase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

.apex/src/objects/PurchaseLine__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PurchaseId__c</fullName>
        <label>Purchase</label>
        <referenceTo>Purchase__c</referenceTo>
        <relationshipLabel>PurchaseLines</relationshipLabel>
        <relationshipName>PurchaseLines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>UnitCost__c</fullName>
        <label>UnitCost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>PurchaseLine</label>
    <nameField>
        <label>PurchaseLine Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PurchaseLines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PurchaseLineHelper.cls
public class PurchaseLineHelper {
	public static void updatePurchaseTotals(List<PurchaseLine__c> lines) {
		Set<Id> purchaseIds = new Set<Id>();
		for (PurchaseLine__c line : lines) {
			if (line.PurchaseId__c != null) {
				purchaseIds.add(line.PurchaseId__c);
			}
		}

		Map<Id, List<PurchaseLine__c>> linesByPurchase = new Map<Id, List<PurchaseLine__c>>();
		for (PurchaseLine__c pl : [
				SELECT PurchaseId__c, UnitCost__c, Amount__c
				FROM PurchaseLine__c
				WHERE PurchaseId__c IN :purchaseIds
		]) {
			if (!linesByPurchase.containsKey(pl.PurchaseId__c)) {
				linesByPurchase.put(pl.PurchaseId__c, new List<PurchaseLine__c>());
			}
			linesByPurchase.get(pl.PurchaseId__c).add(pl);
		}

		List<Purchase__c> updates = new List<Purchase__c>();

		for (Id purchaseId : linesByPurchase.keySet()) {
			List<PurchaseLine__c> plList = linesByPurchase.get(purchaseId);
			Integer totalItems = 0;
			Decimal grandTotal = 0;

			for (PurchaseLine__c line : plList) {
				totalItems += line.Amount__c == null ? 0 : Integer.valueOf(line.Amount__c);
				grandTotal += (line.UnitCost__c != null ? line.UnitCost__c : 0) * (line.Amount__c != null ? line.Amount__c : 0);
			}

			updates.add(new Purchase__c(
					Id = purchaseId,
					TotalItems__c = totalItems,
					GrandTotal__c = grandTotal
			));
		}

		if (!updates.isEmpty()) {
			update updates;
		}
	}
}